sudo: false
language: python
cache:
  pip: true
matrix:
  include:
  - python: "2.7"
    env:
    - TOXENV=pep8
    - UPPER_CONSTRAINTS_FILE=https://raw.githubusercontent.com/sapcc/requirements/stable/stein-m3/upper-constraints.txt
install:
- pip install tox-travis
script: tox
